FROM projectatomic/atomicapp:0.1.12

MAINTAINER Jan Kaluza <jkaluza@redhat.com>

LABEL io.projectatomic.nulecule.specversion 0.0.2

LABEL Build docker build --rm --tag testing/nginx-frontend-atomicapp .


ADD Nulecule /application-entity/
ADD artifacts/ /application-entity/artifacts/
