apiVersion: v1
kind: Pod
metadata:
  name: webapp-wordpress
  labels:
    app: webapp-wordpress
spec:
  containers:
    - name: webapp-wordpress
      image: microwebapps/wordpress
      ports:
        - containerPort: 80
      env:
        - name: WORDPRESS_DB_PASSWORD
          value: $db_password
        - name: WORDPRESS_DB_USER
          value: $db_user
        - name: WORDPRESS_PATH
          value: $mwa_alias
