FROM projectatomic/atomicapp:latest

MAINTAINER Jan Kaluza <jkaluza@redhat.com>

LABEL io.projectatomic.nulecule.specversion 0.0.1-alpha

LABEL Build docker build --rm --tag testing/webapp-owncloud-atomicapp .


ADD Nulecule /application-entity/
ADD artifacts/ /application-entity/artifacts/
