FROM projectatomic/atomicapp:0.0.1

MAINTAINER Jan Kaluza <jkaluza@redhat.com>

LABEL io.projectatomic.nulecule.specversion 0.0.1-alpha

LABEL Build docker build --rm --tag testing/mwa-haproxy-frontend-atomicapp .


ADD Nulecule /application-entity/
ADD artifacts/ /application-entity/artifacts/
